spring:
  application:
    name: yudao-module-iot-plugin-http

yudao:
  iot:
    plugin:
      common:
        upstream-url: http://127.0.0.1:48080
        downstream-port: 8093
      http:
        server-port: 8092
