# EMQX组件默认配置
yudao:
  iot:
    component:
      # 核心组件配置
      core:
        plugin-key: emqx # 插件的唯一标识
      # EMQX组件配置
#      emqx:
#        enabled: true        # 启用EMQX组件
#        mqtt-host: 127.0.0.1 # MQTT服务器主机地址
#        mqtt-port: 1883      # MQTT服务器端口
#        mqtt-username: yudao # MQTT服务器用户名
#        mqtt-password: 123456 # MQTT服务器密码
#        mqtt-ssl: false      # 是否启用SSL
#        mqtt-topics:         # 订阅的主题列表
#          - "/sys/#"
#        auth-port: 8101      # 认证端口
