# ==================== IoT 网关本地开发环境配置 ====================

--- #################### 消息队列相关 ####################

# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  name-server: 127.0.0.1:9876 # RocketMQ Namesrv

--- #################### IoT 网关相关配置 ####################

yudao:
  iot:
    # 网关配置
    gateway:
      # 设备 RPC 配置
      rpc:
        url: http://127.0.0.1:48080 # 主程序 API 地址
      # 设备 Token 配置
      token:
        secret: yudaoIotGatewayTokenSecret123456789 # Token 密钥，至少32位

      # 协议配置
      protocol:
        # ====================================
        # 针对引入的 HTTP 组件的配置
        # ====================================
        http:
          enabled: true
          server-port: 8092
        # ====================================
        # 针对引入的 EMQX 组件的配置
        # ====================================
        emqx:
          enabled: false
          http-port: 8090                       # MQTT HTTP 服务端口
          mqtt-host: 127.0.0.1                  # MQTT Broker 地址
          mqtt-port: 1883                       # MQTT Broker 端口
          mqtt-username: admin                  # MQTT 用户名
          mqtt-password: public                 # MQTT 密码
          mqtt-client-id: iot-gateway-mqtt      # MQTT 客户端 ID
          mqtt-ssl: false                       # 是否开启 SSL
          mqtt-topics:
            - "/sys/#"                         # 系统主题

    # 消息总线配置
    message-bus:
      type: redis # 本地开发使用 RocketMQ

--- #################### 日志相关配置 ####################

# 开发环境日志配置
logging:
  level:
    # 开发环境详细日志
    cn.iocoder.yudao.module.iot.gateway.protocol.mqtt: DEBUG
    cn.iocoder.yudao.module.iot.gateway.protocol.http: DEBUG
    # MQTT 客户端日志
#    io.vertx.mqtt: DEBUG