spring:
  application:
    name: iot-gateway-server
  profiles:
    active: local # 默认激活本地开发环境

--- #################### 消息队列相关 ####################

# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  name-server: 127.0.0.1:9876 # RocketMQ Namesrv
  # Producer 配置项
  producer:
    group: ${spring.application.name}_PRODUCER # 生产者分组

--- #################### IoT 网关相关配置 ####################

yudao:
  iot:
    # 消息总线配置
    message-bus:
      type: redis # 消息总线的类型

    # 网关配置
    gateway:
      # 设备 RPC 配置
      rpc:
        url: http://127.0.0.1:48080 # 主程序 API 地址
        connect-timeout: 30s
        read-timeout: 30s
      # 设备 Token 配置
      token:
        secret: yudaoIotGatewayTokenSecret123456789 # Token 密钥，至少32位
        expiration: 7d

      # 协议配置
      protocol:
        # ====================================
        # 针对引入的 HTTP 组件的配置
        # ====================================
        http:
          enabled: true
          server-port: 8092
        # ====================================
        # 针对引入的 EMQX 组件的配置
        # ====================================
        emqx:
          enabled: false
          http-port: 8090                       # MQTT HTTP 服务端口
          mqtt-host: 127.0.0.1                  # MQTT Broker 地址
          mqtt-port: 1883                       # MQTT Broker 端口
          mqtt-username: admin                  # MQTT 用户名
          mqtt-password: public                 # MQTT 密码
          mqtt-client-id: iot-gateway-mqtt      # MQTT 客户端 ID
          mqtt-ssl: false                       # 是否开启 SSL
          mqtt-topics:
            - "/sys/#"                          # 系统主题
        # ====================================
        # 针对引入的 TCP 组件的配置
        # ====================================
        tcp:
          enabled: true
          server-port: 8093
          server-host: 0.0.0.0

--- #################### 日志相关配置 ####################

# 基础日志配置
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径
  level:
    # 应用基础日志级别
    cn.iocoder.yudao.module.iot.gateway: INFO
    org.springframework.boot: INFO
    # RocketMQ 日志
    org.apache.rocketmq: WARN
    # MQTT 客户端日志
    # io.vertx.mqtt: DEBUG
    # 开发环境详细日志
    cn.iocoder.yudao.module.iot.gateway.protocol.emqx: DEBUG
    cn.iocoder.yudao.module.iot.gateway.protocol.http: DEBUG
    # 根日志级别
    root: INFO

debug: false
