spring:
  application:
    name: iot-gateway-server
  profiles:
    active: local # 默认激活本地开发环境

--- #################### 消息队列相关 ####################

# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  # Producer 配置项
  producer:
    group: ${spring.application.name}_PRODUCER # 生产者分组

--- #################### IoT 网关相关配置 ####################

yudao:
  iot:
    # 网关配置
    gateway:
      # 设备 RPC 配置
      rpc:
        connect-timeout: 30s
        read-timeout: 30s
      # 设备 Token 配置
      token:
        expiration: 7d

      # 协议配置
      protocol:
        # ====================================
        # 针对引入的 HTTP 组件的配置
        # ====================================
        http:
          enabled: true
        # ====================================
        # 针对引入的 EMQX 组件的配置
        # ====================================
        emqx:
          enabled: false
          mqtt-ssl: false
          mqtt-topics:
            - "/sys/#"                         # 系统主题
        # ====================================
        # 针对引入的 TCP 组件的配置
        # ====================================
        tcp:
          enabled: false

    # 消息总线配置
    message-bus:
      type: redis # 消息总线的类型

--- #################### 日志相关配置 ####################

# 基础日志配置
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径
  level:
    # 应用基础日志级别
    cn.iocoder.yudao.module.iot.gateway: INFO
    org.springframework.boot: INFO
    # RocketMQ 日志
    org.apache.rocketmq: WARN
    # 根日志级别
    root: INFO

debug: false
