spring:
  application:
    name: yudao-module-iot-http-plugin

# MQTT-RPC 配置
mqtt:
  broker: tcp://chaojiniu.top:1883
  username: haohao
  password: ahh@123456
  clientId: mqtt-rpc-client-${random.int}
  requestTopic: rpc/request
  responseTopicPrefix: rpc/response/
